"""delete a column in deal table

Revision ID: 32119b59581e
Revises: 36bbe2a8ee98
Create Date: 2025-05-09 05:40:12.180833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32119b59581e'
down_revision: Union[str, None] = '36bbe2a8ee98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deal', 'business_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal', sa.Column('business_size', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
