"""added a column logo

Revision ID: 87f190bffde2
Revises: 3dd0708a1c76
Create Date: 2025-05-17 15:15:30.383919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87f190bffde2'
down_revision: Union[str, None] = '3dd0708a1c76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subadmin', sa.Column('logo', sa.String(), nullable=False))
    op.add_column('subadmin', sa.Column('username', sa.String(), nullable=False))
    op.alter_column('subadmin', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('subadmin', 're_entered_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('subadmin', 'app_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('subadmin', 'invite_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('subadmin_user_id_key', 'subadmin', type_='unique')
    op.create_unique_constraint(None, 'subadmin', ['username'])
    op.drop_column('subadmin', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subadmin', 'invite_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subadmin', 'app_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subadmin', 're_entered_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subadmin', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
