"""added a column in kyc table: pan_aadhaar_linked [bool]

Revision ID: b367df37d3b7
Revises: 32119b59581e
Create Date: 2025-05-11 13:58:20.754679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b367df37d3b7'
down_revision: Union[str, None] = '32119b59581e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kyc', sa.Column('pan_aadhaar_linked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kyc', 'pan_aadhaar_linked')
    # ### end Alembic commands ###
