"""table relationship changes

Revision ID: e6df51c350e4
Revises: 87f190bffde2
Create Date: 2025-05-18 00:51:01.253811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6df51c350e4'
down_revision: Union[str, None] = '87f190bffde2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Step 1: Update deal.fund_manager_id to reference subadmin.id
    op.execute("""
        DELETE FROM deal
        WHERE fund_manager_id NOT IN (SELECT id FROM subadmin);
    """)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deal', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('deal', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('deal', 'agreed_to_terms',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint('deal_fund_manager_id_fkey', 'deal', type_='foreignkey')
    op.create_foreign_key(None, 'deal', 'subadmin', ['fund_manager_id'], ['id'])
    op.alter_column('subadmin', 'logo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subadmin', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subadmin', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subadmin', 're_entered_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subadmin', 'app_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subadmin', 'invite_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subadmin', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('subadmin_invite_code_key', 'subadmin', type_='unique')
    op.create_index(op.f('ix_subadmin_invite_code'), 'subadmin', ['invite_code'], unique=True)
    op.create_foreign_key(None, 'user', 'subadmin', ['invitation_code'], ['invite_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_index(op.f('ix_subadmin_invite_code'), table_name='subadmin')
    op.create_unique_constraint('subadmin_invite_code_key', 'subadmin', ['invite_code'])
    op.alter_column('subadmin', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('subadmin', 'invite_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subadmin', 'app_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subadmin', 're_entered_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subadmin', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subadmin', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subadmin', 'logo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'deal', type_='foreignkey')
    op.create_foreign_key('deal_fund_manager_id_fkey', 'deal', 'user', ['fund_manager_id'], ['id'])
    op.alter_column('deal', 'agreed_to_terms',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('deal', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('deal', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
